### PR TITLE
Fixing some issues

### PR DESCRIPTION
**Pull request by mihaikelemen**
- fixes invalid method used 
- fixes _cURL error 3: IPv6 numerical address used in URL without brackets_

### CODE REVIEW

**Comment by nathan-fiscaletti** [comment]
Could you add one more commit fixing the StyleCI issues with this PR before I merge it?

https://github.styleci.io/analyses/KZD0oj?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mihaikelemen** [comment]
Sure. I'll make the changes so it complies with StyleCI.

**Comment by mihaikelemen** [comment]
@nathan-fiscaletti Sorry for all this spam, due to style compliance. I made a code refactoring to make it more clean.

Mihai.

**Comment by nathan-fiscaletti** [comment]
The python mirror has been updated with ipv6 formatted IP address support as well:

https://github.com/nathan-fiscaletti/ipstackgeo-py/commit/803847a968e2e33b5ad4ca4d2c4cfcd4603712a4

**Pull request merged**
